name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git fetch upstream
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Sync with upstream/main
        run: |
          git checkout main
          if git diff --quiet HEAD..upstream/main; then
            echo "✅ Fork is already up to date."
          else
            git merge upstream/main --allow-unrelated-histories --no-edit
            git push origin main
            echo "✅ Synced fork with upstream."
          fi
