name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}  # Authenticate checkout for pushing later

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://${{ secrets.GH_PAT }}@github.com/SIAM-VIT/SIAM-Website.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Sync with upstream/main
        run: |
          git checkout main
          if git diff --quiet HEAD..upstream/main; then
            echo "✅ Fork is already up to date."
          else
            git merge upstream/main --allow-unrelated-histories --no-edit
            git push https://${{ secrets.GH_PAT }}@github.com/Oik17/SIAM-Website.git HEAD:main
            echo "✅ Synced fork with upstream."
          fi
