name: Sync Fork with Upstream

on:
  schedule:
     - cron: '*/15 * * * *'  
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/SIAM-VIT/SIAM-Website.git
          git fetch upstream

      - name: Sync with upstream if needed
        run: |
          git checkout main
          if git diff --quiet HEAD..upstream/main; then
            echo "✅ Fork is up to date."
          else
            git pull upstream main
            git push origin main
            git commit --allow-empty -m "Sync via GitHub Action"
            git push origin main
          fi
