name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://${{ secrets.GH_PAT }}@github.com/SIAM-VIT/SIAM-Website.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Sync with upstream/main
        id: sync
        run: |
          git checkout main
          if git diff --quiet HEAD..upstream/main; then
            echo "✅ Fork is already up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            git merge upstream/main --allow-unrelated-histories --no-edit
            git push https://${{ secrets.GH_PAT }}@github.com/Oik17/SIAM-Website.git HEAD:main
            echo "✅ Synced fork with upstream."
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Append hidden sync log to README
        if: steps.sync.outputs.updated == 'true'
        run: |
          echo "<!-- $(date -u '+%Y-%m-%d %H:%M:%S') UTC: Synced with upstream by GitHub Actions bot -->" >> README.md
          git add README.md
          git commit -m "docs: append sync log entry"
          git push https://${{ secrets.GH_PAT }}@github.com/Oik17/SIAM-Website.git HEAD:main
